### ISSUE TITLE
Frontend roadmap to 0.2.0 

### ISSUE THREAD

**Issue by jbitshine** [jbitshine/riverflow#2]
- [ ] Category CRUD requests and views
- [ ] River CRUD requests and views
  - [ ] Share river between users
- [ ] Steps CRUD requests and views
- [ ] Paths CRUD requests and views
- [ ] Targets CRUD requests and views
- [ ] Stream types CRUD requests and views
- [ ] Streams CRUD requests and views
- [ ] Stream comments CRUD requests and views
